### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by pickelsandcarrots316** [haproxytech/dataplaneapi#13] opened 2019-07-12 16:29 UTC
Whenever I run dataplaneapi, I get the following error message:
`time="2019-07-12T16:22:57Z" level=fatal msg="Error starting Data Plane API: runtime error: slice bounds out of range"`

I get this both when building against source or downloading the pre-built binary.  The error occurs on both Ubuntu 18.04 and CentOS 7.6.  I'm running go version go1.12.7 linux/amd64 on both.

**Comment by mjuraga** [comment] 2019-07-15 08:51
Hi, I cannot reproduce your error, can you please show me what cli options are you using when starting dataplaneapi?

**Comment by pickelsandcarrots316** [comment] 2019-07-15 13:34
Running it with no options will generate this error, as will running it with
`./dataplaneapi -b /usr/local/sbin/haproxy -m /var/run/haproxy.sock -c /etc/haproxy/haproxy.cfg -u haproxy`

running it with `-v` or `-h` will not crash

**Comment by mjuraga** [comment] 2019-07-16 09:05
Hi, in commit https://github.com/haproxytech/dataplaneapi/commit/2c3e099386439654ce29d142a16249a94ce9c860 I added extra logging information in this case. Can you try and build with the latest master source and show me the output of the log?

**Comment by pickelsandcarrots316** [comment] 2019-07-16 13:55
After pulling the latest, it doesn't crash.  Runs like I expect it to.

**Comment by CRCinAU** [comment] 2019-07-19 02:02
We get the same issue when running release 1.1.0.

Earlier version run fine.

**Comment by mjuraga** [comment] 2019-07-19 07:27
Can you paste the log output?

**Comment by CRCinAU** [comment] 2019-07-19 07:41
```
time="2019-07-19T17:39:27+10:00" level=fatal msg="Error starting Data Plane API: runtime error: slice bounds out of range
 Stacktrace from panic: 
goroutine 1 [running]:
runtime/debug.Stack(0xc00062b348, 0xb531e0, 0x12ec2d0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/haproxytech/dataplaneapi.configureAPI.func1()
	/home/mjuraga/projects/go/src/github.com/haproxytech/dataplaneapi/configure_data_plane.go:111 +0x57
panic(0xb531e0, 0x12ec2d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/haproxytech/config-parser/parsers.(*OptionHttpchk).Parse(0xc0007fe5c0, 0xc0000278f6, 0x10, 0xc00036e100, 0x2, 0x2, 0xc0004ef230, 0x3, 0x3, 0x0, ...)
	/home/mjuraga/projects/go/src/github.com/haproxytech/config-parser/parsers/option-httpchk.go:66 +0x639
github.com/haproxytech/config-parser.(*Parser).ProcessLine(0xc000437a70, 0xc0000278f6, 0x10, 0xc00036e100, 0x2, 0x2, 0xc0004ef230, 0x3, 0x3, 0x0, ...)
	/home/mjuraga/projects/go/src/github.com/haproxytech/config-parser/parser.go:335 +0x143
github.com/haproxytech/config-parser.(*Parser).ParseData(0xc000437a70, 0xc000027000, 0x456f, 0x476f, 0xc000027000)
	/home/mjuraga/projects/go/src/github.com/haproxytech/config-parser/parser.go:480 +0xb71
github.com/haproxytech/config-parser.(*Parser).LoadData(0xc000437a70, 0x7ffe8b3e7f32, 0x22, 0x837060, 0xc000000180)
	/home/mjuraga/projects/go/src/github.com/haproxytech/config-parser/parser.go:433 +0xa9
github.com/haproxytech/client-native/configuration.(*Client).Init(0xc0000a4320, 0x7ffe8b3e7f32, 0x22, 0x7ffe8b3e7f21, 0xd, 0x100, 0x7ffe8b3e7f87, 0xc, 0x49d3ed, 0x1320df0)
	/home/mjuraga/projects/go/src/github.com/haproxytech/client-native/configuration/configuration.go:110 +0x14a
github.com/haproxytech/dataplaneapi.configureConfigurationClient(0xc2d22d, 0x10, 0x0)
	/home/mjuraga/projects/go/src/github.com/haproxytech/dataplaneapi/configure_data_plane.go:521 +0x113
github.com/haproxytech/dataplaneapi.configureNativeClient(0xda76c0)
	/home/mjuraga/projects/go/src/github.com/haproxytech/dataplaneapi/configure_data_plane.go:498 +0x81
github.com/haproxytech/dataplaneapi.configureAPI(0xc0005c2e00, 0x0, 0x0)
	/home/mjuraga/projects/go/src/github.com/haproxytech/dataplaneapi/configure_data_plane.go:133 +0x146
github.com/haproxytech/dataplaneapi.(*Server).ConfigureAPI(0xc0004d5080)
	/home/mjuraga/projects/go/src/github.com/haproxytech/dataplaneapi/server.go:73 +0x41
main.main()
	/home/mjuraga/projects/go/src/github.com/haproxytech/dataplaneapi/cmd/dataplaneapi/main.go:86 +0xad3"
```

**Comment by mjuraga** [comment] 2019-07-19 07:47
And can you paste the config (the part with option httpchk specifically), it seems to fail there.

**Comment by CRCinAU** [comment] 2019-07-19 07:50
Ahhh - I'm going to guess this is due to this workaround that has been in use for quite a while for passing a vhost to a backend:

option httpchk GET /httpchk.html HTTP/1.0\r\nHost:\ <$domain>

**Comment by mjuraga** [comment] 2019-07-19 08:56
Actually it is a bug in a package config-parser: https://github.com/haproxytech/config-parser/pull/5

It is with having ```option httpchk``` set without further arguments. This should be fixed soon, I will let you know.

**Comment by mjuraga** [comment] 2019-07-19 12:19
Should be fixed with c716ebf

**Comment by CRCinAU** [comment] 2019-07-19 16:31
Thanks for the quick response. We'll try this out again when the next release drops.

**Closed** 2019-07-30 13:03 UTC
Labels: bug

**Comment by mjuraga** [comment] 2019-08-06 17:02
This is release v1.1.1
