### ISSUE TITLE
Canceling of failed transactions fails and does not decrement internal counter correctly

### ISSUE THREAD

**Issue by schegi** [haproxytech/dataplaneapi#173] opened 2021-02-25 09:30 UTC
Hi,

it seems like canceling failed transactions does not decrement the internal active transactions counter correctly. Therefore after several failed (and canceled) transactions it is no longer possible to open new transactions, only a restart of the dataplane api helps in this situation.

To reproduce, do the following:

1. open 20 transactions (POST on http://XXX:5555/v2/services/haproxy/transactions). 20 files in /tmp/haproxy, one for each transaction with id in name.
2. try to commit those transactions sequentially (PUT on http://XXX:5555/v2/services/haproxy/transactions/ID). This leads to the first commit to succeed and all the rest to fail. If you now get all transactions (GET on http://XXX:5555/v2/services/haproxy/transactions) from dataplane API, you'll get 19 transaction with status 'failed'. /tmp/haproxy is empty, all failed transaction files moved to /tmp/haproxy/failed (19 files in total).
3. Cancel all the failed transactions (DEL on http://XXX:5555/v2/services/haproxy/transactions/ID). This always results with {"code": 400,  "message": "20: Transaction <ID> does not exist"} if transaction ID has status "failed". Maybe this has something to do with it. After canceling the transactions, getting all transaction (GET on http://XXX:5555/v2/services/haproxy/transactions) gives you a empty list, so no active transactions. /tmp/haproxy and /tmp/haproxy/failed are accordingly empty
4. try to open 20 transactions again. Only the first call succeeds, the rest of the calls will fail with "cannot start a new transaction, reached the maximum amount of 20 active transactions available". one file shows up under /tmp/haproxy
5. Getting all transactions gives you a list with exactly one transaction.
6. If you now restart the dataplane api, you are again able to start transaction up to the limit of 20.

Greets
Stefan

**Comment by oktalz** [comment] 2021-02-25 12:14
@schegi this indeed looks like a bug, we will investigate it.

**Comment by schegi** [comment] 2021-03-01 13:46
I looked into it, for me it seems like it has to do with the fact that on failed transaction commit the deletion of the transactionID from the parser (https://github.com/haproxytech/client-native/blob/26193e15aaeb09096451e5f6818d669f4043d112/configuration/transaction.go#L512). On deletion of this (failed) transaction then, the check (https://github.com/haproxytech/dataplaneapi/blob/bb617cab4c70615d52c38cceb8a16f2172dbdb35/handlers/transaction.go#L143) fails and therefore the counter is never decreased. Not shure how you like to handle this, easiest  probably correct beaviour, would be to delete the removal the transactionID from the parser, the transaction fails but it still exists and must be canceled from my understanding.

Greets
Stefan

**Comment by prometherion** [comment] 2021-03-01 14:16
Hey @schegi, thanks for the bug report!

We just released a new commit trying to tackle this issue down (https://github.com/haproxytech/dataplaneapi/commit/bb617cab4c70615d52c38cceb8a16f2172dbdb35), feedback is highly appreciated.

When a previous transaction is marked as failed, the rate limit is decreased, leaving room for new transactions starts.

**Comment by schegi** [comment] 2021-03-01 14:44
Ok, this also works for transactions, it only fixes the counter issue. Not the fact that canceling a failed transaction (the only way to get rid of the transaction file on the node) still returns a 400, due to the missing transactionID in the parser in client-native (always returns with {"code": 400, "message": "20: Transaction <ID> does not exist"}). 

Greets
Stefan

**Comment by prometherion** [comment] 2021-03-01 15:51
I'd say this is expected behavior, please correct me @oktalz if I'm wrong.

If I try to commit a transaction that is outdated due to progressed `version` or broken, there's no way to recover it and it's marked as `failed`: there's no chance to fix it except starting a new one in order to get the incremented version number or avoid the broken (sic) logic that led to that issue.

**Comment by schegi** [comment] 2021-03-01 15:55
Yes but why getting an error on removal (cancel) of such a failed transaction? And why a 400? If i don't remove (cancel) these failed transactios i might end up with countless failed transaction files.

**Comment by oktalz** [comment] 2021-03-01 16:10
400 is not ideal here, I agree on that.

the best solution actually is that when one is successful, all others that were open with same (or lower) version are automatically canceled and removed, since none of them can be successful due to incorrect version of file.

but also dataplaneapi keeps the list of all of them so it does not return 400 or 404 but 409 conflict (or even 410 Gone) if you try to delete it manually later

similarly for any failed transaction, even if there is no duplicates dataplaneapi should return 404/410 because if transaction fails, we do not need to keep resources (or at least by default keep only certain number of them in failed folder)

**Comment by schegi** [comment] 2021-03-03 16:47
Another thing, it seems like your fix only applies to cases where the commit of the transaction fails due to a 409 (i assume version error) as provoked by my example. But initially i came across this due to failed transactions cause of failed config verification on commit. And still it seems like i have this problem with an transaction counter which is not devreased on commit failures. Could it be the case that the return code is different in such cases. I'll try to verify this.

**Closed** 2021-03-11 10:40 UTC
