### ISSUE TITLE
Dataplane API fails to startup

### ISSUE THREAD

**Issue by Fireant456** [haproxytech/dataplaneapi#158] opened 2021-01-31 01:44 UTC
I am really stumped as to why this deployment of HAProxy in Docker is not working while I have had 2 other deployments of the Dataplane API work just fine with the same config added (pictured below) to all 3 deployments. I keep getting the error shown at the bottom of this issue. Users are clearly defined and still the api program fails to launch and cause the proxy not to boot at all.

![image](https://user-images.githubusercontent.com/1479965/106372091-dbf8e000-6331-11eb-903a-9197e9dc4de6.png)
Our full config: https://pastebin.pl/view/6099676d (replaced passwords, domain names and variable names)
docker-compose.yml file: 
![image](https://user-images.githubusercontent.com/1479965/106372245-76a5ee80-6333-11eb-98c8-ab5e3a2821e6.png)

![image](https://user-images.githubusercontent.com/1479965/106372225-4d855e00-6333-11eb-8337-5836b3a7320b.png)

**Comment by mjuraga** [comment] 2021-03-19 11:48
Duplicate of https://github.com/haproxytech/dataplaneapi/issues/164

**Closed by mjuraga** 2021-03-19 11:48 UTC

**Comment by Fireant456** [comment] 2021-03-19 12:04
@mjuraga I do not believe this is a duplicate. This is a different error and my issue is not resolved by the steps suggested in #164

**Comment by Fireant456** [comment] 2021-03-19 12:15
Found the issue 🤦 seems to be some windows to unix CR characters messing with the config. Running dos2unix on the config file resolves the issue. https://github.com/haproxytech/dataplaneapi/issues/29#issuecomment-576690615

**Comment by mjuraga** [comment] 2021-03-19 12:32
Sry @Fireant456, I mistakenly duplicated the issue with the other one. Happy you resolved your issue.
