### ISSUE TITLE
"Using the Data Plane API" docs don't match spec or code

### ISSUE THREAD

**Issue by bren-doyle** [haproxytech/dataplaneapi#163] opened 2021-02-09 18:34 UTC
URL
https://www.haproxy.com/documentation/hapee/latest/reference/dataplaneapi/

ALC example has:
> url -X POST --user admin:mypassword \
> -H "Content-Type: application/json" \
> -d '{"id": 0, "acl_name": "is_api", "criterion": "path_beg", "value": "/api"}' \
> "http://localhost:5555/v2/services/haproxy/configuration/acls?parent_type=frontend&parent_name=test_frontend&version=4"
Code returns:
{"code":602,"message":"index in body is required"}

And API sec says nothing of "id" but does mention "index" So I think in the example it should be "index" not "id"
But also neither say what the "index" refers to. Is it a reference to the ACL, i.e if I create two ALCs one has
index 0, the other index 1?? Can you point me to some documentation.

**Comment by NickMRamirez** [comment] 2021-02-12 15:45
Duplicate of https://github.com/haproxytech/dataplaneapi/issues/151

**Closed** 2021-03-19 11:47 UTC
