### ISSUE TITLE
Missing NIL Check in for configStorage.Dataplaneapi 

### ISSUE THREAD

**Issue by saurabh-kushwah** [haproxytech/dataplaneapi#303] opened 2023-05-09 17:31 UTC
From the commit history the nil pointer check has been added 2 months ago, but on checking out the latest tag version ex. v2.7.4, looks like the nil check is missing. 

https://github.com/haproxytech/dataplaneapi/blob/v2.7.4/dataplaneapi_configuration.go#L38
```go
if configStorage.Dataplaneapi.EnabledListeners != nil && !misc.HasOSArg("", "scheme", "") {
  server.EnabledListeners = *configStorage.Dataplaneapi.EnabledListeners
}
```

https://github.com/haproxytech/dataplaneapi/blob/master/dataplaneapi_configuration.go#L38
```go
if configStorage.Dataplaneapi != nil && configStorage.Dataplaneapi.EnabledListeners != nil && !misc.HasOSArg("", "scheme", "") {
  server.EnabledListeners = *configStorage.Dataplaneapi.EnabledListeners
}
```

**Comment by mjuraga** [comment] 2023-05-09 19:55
Duplicate of https://github.com/haproxytech/dataplaneapi/issues/293

Fixed in https://github.com/haproxytech/dataplaneapi/releases/tag/v2.7.5

**Closed by mjuraga** 2023-05-09 19:55 UTC
