### ISSUE TITLE
v2.2 not working inside docker container

### ISSUE THREAD

**Issue by spn91** [haproxytech/dataplaneapi#164] opened 2021-02-10 13:26 UTC
Hello!
I'm trying to use haproxytech/haproxy-debian:2.3 docker image. In this image the HAProxy Data Plane API v2.2.0 68bd22b is builtin. 
But the container won't start. 
Log:
``` 
[NOTICE] 040/131234 (1) : New program 'api' (8) forked
[NOTICE] 040/131234 (1) : New worker #1 (9) forked
time="2021-02-10T13:12:34Z" level=info msg="HAProxy Data Plane API v2.2.0 68bd22b"
time="2021-02-10T13:12:34Z" level=info msg="Build from: https://github.com/haproxytech/dataplaneapi.git"
time="2021-02-10T13:12:34Z" level=info msg="Build date: 2021-01-15T13:48:22Z"
time="2021-02-10T13:12:34Z" level=fatal msg="The configuration file is not declared in the HAPROXY_CFGFILES environment variable, cannot start."
[NOTICE] 040/131234 (1) : haproxy version is 2.3.5-5902ad9
[NOTICE] 040/131234 (1) : path to executable is /usr/local/sbin/haproxy
[ALERT] 040/131234 (1) : Current program 'api' (8) exited with code 1 (Exit)
[ALERT] 040/131234 (1) : exit-on-failure: killing every processes with SIGTERM
[ALERT] 040/131234 (1) : Current worker #1 (9) exited with code 143 (Terminated)
[WARNING] 040/131234 (1) : All workers exited. Exiting... (1)
```

Config:

```
### Enable dataplane api user ###
userlist dataplane-api
  user dataplaneapi insecure-password secret


### Start dataplaneapi ###
program api
    command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /usr/local/etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist dataplane-api
    no option start-on-reload
 
global
  log /dev/log  local0
  log /dev/log  local1 notice
  user haproxy
  group haproxy
  daemon
  master-worker
  maxconn 16384
  ca-base /etc/ssl/certs
  crt-base /etc/haproxy/ssl
  ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
 
 ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
   
  ### Enable stats socket for controlling
  stats socket /var/run/haproxy.sock mode 600 level admin
  stats timeout 2m
 
 
defaults
  mode                    http
  log                     global
  option                  httplog
  option                  dontlognull
  option dontlog-normal
  option http-server-close
  option forwardfor       except 127.0.0.0/8
  option                  redispatch
 
  retries                 3
  timeout http-request    5s
  timeout queue           30s
  timeout connect         5s
  timeout client          30s
  timeout server          30s
  timeout http-keep-alive 10s
  timeout check           5s
  balance leastconn

### HAProxy Statistics
listen snmpd-haproxy-stats
  bind :8080
  stats enable
  stats hide-version
  stats uri /
  stats refresh 10s
  mode http
  acl white_list src X.X.X.X
  tcp-request content accept if white_list
  tcp-request content reject
  http-request set-log-level silent
  timeout client  30s
  timeout server  30s
  timeout connect  5s


```
I think, this has to do with the following line of your code, which was changed with the 2.2 release.

https://github.com/haproxytech/dataplaneapi/blob/0b85f27209a05520447e8f6b989d082caa725fba/configure_data_plane.go#L146

I know that this was introduced to terminate if the config file is missing, but it is not missing. It seems that the api process just can't access the HAPROXY_CFGFILES environment variable when running inside a container. Because of this it was working with dataplane api version < 2.2.
Everythings works as expected when tested without docker.

**Comment by dkorunic** [comment] 2021-02-10 13:32
@spunti Wrong path to config file (`--config-file usr/local/etc/haproxy/haproxy.cfg`) is being used. It seems that you have missed a leading slash here, ie. `/usr/local/...` vs `usr/local/...`.

**Comment by spunti** [comment] 2021-02-10 13:35
@dkorunic sry, this was a typo which resulted from debugging. It is also not working with `/usr/...`

**Comment by dkorunic** [comment] 2021-02-10 14:05
I can confirm this seems to be a bug.

**Comment by oktalz** [comment] 2021-02-10 14:37
Also confirming this is a bug in dataplane, currently you can't have same file for 
`--config-file` and `--userlist-file` options. 
but if you omit `--userlist-file` option it will use `--config-file` file to read auth data :)

fix incoming, thx @spunti for reporting this

**Comment by spunti** [comment] 2021-02-10 14:40
@oktalz i don't think that this is the problem. The `--userlist-file` was also just there for testing if I would need to set this option. If you remove it, it doesn't work either

**Comment by spunti** [comment] 2021-02-10 15:49
@oktalz I have now tried again to confirm that it does not work with it. But strangely enough it works now. Maybe I got confused while testing and had never removed the `--userlist-file`.
But at least we found a bug with it.

**Comment by Fireant456** [comment] 2021-03-19 11:55
Has this been fixed? I attempted this on 2.1.17 and still same behavior...

**Comment by Fireant456** [comment] 2021-03-19 12:06
I keep getting the following error instead, same exact api config as this original poster on HaProxy-Alpine Docker container on version 2.1.12. This looks like it runs version 2.2.0 of the DataplaneAPI...

![image](https://user-images.githubusercontent.com/1479965/111777724-a5dfd300-8881-11eb-8ab5-2964199f039c.png)

**Comment by Fireant456** [comment] 2021-03-19 12:07
I made an issue #158 but it was closed as a duplicate which I am not sure it is actually a duplicate...

**Comment by Fireant456** [comment] 2021-03-19 12:15
Found the issue 🤦 seems to be some windows to unix CR characters messing with the config. Running dos2unix on the config file resolves the issue. https://github.com/haproxytech/dataplaneapi/issues/29#issuecomment-576690615

**Closed** 2021-04-08 12:10 UTC
Labels: bug
